version: '3.7'
services:
    db:
        image: postgres
        container_name: 1nil-db
        environment:
            - POSTGRES_USER=postgres  
            - POSTGRES_PASSWORD=very_secret_db_password         
        expose:
            - 5432
        volumes:
            - ./db_scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    stats:
        container_name: 1nil-stats
        build:
            context: ./
            dockerfile: ./services/stats/Dockerfile
        command: bash -c "python3 -m services.stats.service"
        expose: 
            - 50052
        depends_on: 
            db: 
                condition: service_healthy
    
    mantle:
        container_name: 1nil-mantle
        build:
            context: ./
            dockerfile: ./services/mantle/Dockerfile
        command: bash -c "cd services/mantle; flask run --host 0.0.0.0"
        expose: 
            - 5000
        ports: 
            - '5000:5000'
        depends_on: 
            - stats
        environment: 
            - STATS_GRPC_HOST='1nil-stats'
            - DATABASE_URL = "postgresql://postgres:very_secret_db_password@1nil-db:5432"
            - APP_SECRET_KEY = "1nil"
            - FLASK_APP=app.py
            - PYTHONUNBUFFERED=1
volumes:
    db:  