# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\"G\n\x11\x43reateGameRequest\x12\x10\n\x08homeTeam\x18\x01 \x01(\t\x12\x10\n\x08\x61wayTeam\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\"$\n\x12\x43reateGameResponse\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"!\n\x0fGetShotsRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"\xa6\x01\n\x10GetShotsResponse\x12\x33\n\x08homeTeam\x18\x01 \x01(\x0b\x32!.stats.GetShotsResponse.TeamShots\x12\x33\n\x08\x61wayTeam\x18\x02 \x01(\x0b\x32!.stats.GetShotsResponse.TeamShots\x1a(\n\tTeamShots\x12\x1b\n\x05shots\x18\x01 \x03(\x0b\x32\x0c.stats.Shots\"Y\n\x05Shots\x12\x0e\n\x06isGoal\x18\x01 \x01(\x08\x12\x12\n\nisOnTarget\x18\x02 \x01(\x08\x12\x0e\n\x06scorer\x18\x03 \x01(\t\x12\x0e\n\x06\x61ssist\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\x05\"\x11\n\x0fGetFoulsRequest\"\x12\n\x10GetFoulsResponse\"\x14\n\x12GetOffsidesRequest\"\x15\n\x13GetOffsidesResponse\"\x10\n\x0eSetShotRequest\"\x11\n\x0fSetShotResponse\"\x10\n\x0eSetFoulRequest\"\x11\n\x0fSetFoulResponse\"\x13\n\x11SetOffsideRequest\"\x14\n\x12SetOffsideResponse\"\x11\n\x0fSetEventRequest\"\x12\n\x10SetEventResponse2\xfe\x03\n\x05Stats\x12\x41\n\nCreateGame\x12\x18.stats.CreateGameRequest\x1a\x19.stats.CreateGameResponse\x12;\n\x08GetShots\x12\x16.stats.GetShotsRequest\x1a\x17.stats.GetShotsResponse\x12;\n\x08GetFouls\x12\x16.stats.GetFoulsRequest\x1a\x17.stats.GetFoulsResponse\x12\x44\n\x0bGetOffsides\x12\x19.stats.GetOffsidesRequest\x1a\x1a.stats.GetOffsidesResponse\x12\x38\n\x07SetShot\x12\x15.stats.SetShotRequest\x1a\x16.stats.SetShotResponse\x12\x38\n\x07SetFoul\x12\x15.stats.SetFoulRequest\x1a\x16.stats.SetFoulResponse\x12\x41\n\nSetOffside\x12\x18.stats.SetOffsideRequest\x1a\x19.stats.SetOffsideResponse\x12;\n\x08SetEvent\x12\x16.stats.SetEventRequest\x1a\x17.stats.SetEventResponseb\x06proto3')



_CREATEGAMEREQUEST = DESCRIPTOR.message_types_by_name['CreateGameRequest']
_CREATEGAMERESPONSE = DESCRIPTOR.message_types_by_name['CreateGameResponse']
_GETSHOTSREQUEST = DESCRIPTOR.message_types_by_name['GetShotsRequest']
_GETSHOTSRESPONSE = DESCRIPTOR.message_types_by_name['GetShotsResponse']
_GETSHOTSRESPONSE_TEAMSHOTS = _GETSHOTSRESPONSE.nested_types_by_name['TeamShots']
_SHOTS = DESCRIPTOR.message_types_by_name['Shots']
_GETFOULSREQUEST = DESCRIPTOR.message_types_by_name['GetFoulsRequest']
_GETFOULSRESPONSE = DESCRIPTOR.message_types_by_name['GetFoulsResponse']
_GETOFFSIDESREQUEST = DESCRIPTOR.message_types_by_name['GetOffsidesRequest']
_GETOFFSIDESRESPONSE = DESCRIPTOR.message_types_by_name['GetOffsidesResponse']
_SETSHOTREQUEST = DESCRIPTOR.message_types_by_name['SetShotRequest']
_SETSHOTRESPONSE = DESCRIPTOR.message_types_by_name['SetShotResponse']
_SETFOULREQUEST = DESCRIPTOR.message_types_by_name['SetFoulRequest']
_SETFOULRESPONSE = DESCRIPTOR.message_types_by_name['SetFoulResponse']
_SETOFFSIDEREQUEST = DESCRIPTOR.message_types_by_name['SetOffsideRequest']
_SETOFFSIDERESPONSE = DESCRIPTOR.message_types_by_name['SetOffsideResponse']
_SETEVENTREQUEST = DESCRIPTOR.message_types_by_name['SetEventRequest']
_SETEVENTRESPONSE = DESCRIPTOR.message_types_by_name['SetEventResponse']
CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

CreateGameResponse = _reflection.GeneratedProtocolMessageType('CreateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMERESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.CreateGameResponse)
  })
_sym_db.RegisterMessage(CreateGameResponse)

GetShotsRequest = _reflection.GeneratedProtocolMessageType('GetShotsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSHOTSREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetShotsRequest)
  })
_sym_db.RegisterMessage(GetShotsRequest)

GetShotsResponse = _reflection.GeneratedProtocolMessageType('GetShotsResponse', (_message.Message,), {

  'TeamShots' : _reflection.GeneratedProtocolMessageType('TeamShots', (_message.Message,), {
    'DESCRIPTOR' : _GETSHOTSRESPONSE_TEAMSHOTS,
    '__module__' : 'stats_pb2'
    # @@protoc_insertion_point(class_scope:stats.GetShotsResponse.TeamShots)
    })
  ,
  'DESCRIPTOR' : _GETSHOTSRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetShotsResponse)
  })
_sym_db.RegisterMessage(GetShotsResponse)
_sym_db.RegisterMessage(GetShotsResponse.TeamShots)

Shots = _reflection.GeneratedProtocolMessageType('Shots', (_message.Message,), {
  'DESCRIPTOR' : _SHOTS,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.Shots)
  })
_sym_db.RegisterMessage(Shots)

GetFoulsRequest = _reflection.GeneratedProtocolMessageType('GetFoulsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFOULSREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetFoulsRequest)
  })
_sym_db.RegisterMessage(GetFoulsRequest)

GetFoulsResponse = _reflection.GeneratedProtocolMessageType('GetFoulsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFOULSRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetFoulsResponse)
  })
_sym_db.RegisterMessage(GetFoulsResponse)

GetOffsidesRequest = _reflection.GeneratedProtocolMessageType('GetOffsidesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOFFSIDESREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetOffsidesRequest)
  })
_sym_db.RegisterMessage(GetOffsidesRequest)

GetOffsidesResponse = _reflection.GeneratedProtocolMessageType('GetOffsidesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOFFSIDESRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.GetOffsidesResponse)
  })
_sym_db.RegisterMessage(GetOffsidesResponse)

SetShotRequest = _reflection.GeneratedProtocolMessageType('SetShotRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETSHOTREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetShotRequest)
  })
_sym_db.RegisterMessage(SetShotRequest)

SetShotResponse = _reflection.GeneratedProtocolMessageType('SetShotResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETSHOTRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetShotResponse)
  })
_sym_db.RegisterMessage(SetShotResponse)

SetFoulRequest = _reflection.GeneratedProtocolMessageType('SetFoulRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETFOULREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetFoulRequest)
  })
_sym_db.RegisterMessage(SetFoulRequest)

SetFoulResponse = _reflection.GeneratedProtocolMessageType('SetFoulResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETFOULRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetFoulResponse)
  })
_sym_db.RegisterMessage(SetFoulResponse)

SetOffsideRequest = _reflection.GeneratedProtocolMessageType('SetOffsideRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETOFFSIDEREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetOffsideRequest)
  })
_sym_db.RegisterMessage(SetOffsideRequest)

SetOffsideResponse = _reflection.GeneratedProtocolMessageType('SetOffsideResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETOFFSIDERESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetOffsideResponse)
  })
_sym_db.RegisterMessage(SetOffsideResponse)

SetEventRequest = _reflection.GeneratedProtocolMessageType('SetEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETEVENTREQUEST,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetEventRequest)
  })
_sym_db.RegisterMessage(SetEventRequest)

SetEventResponse = _reflection.GeneratedProtocolMessageType('SetEventResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETEVENTRESPONSE,
  '__module__' : 'stats_pb2'
  # @@protoc_insertion_point(class_scope:stats.SetEventResponse)
  })
_sym_db.RegisterMessage(SetEventResponse)

_STATS = DESCRIPTOR.services_by_name['Stats']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEGAMEREQUEST._serialized_start=22
  _CREATEGAMEREQUEST._serialized_end=93
  _CREATEGAMERESPONSE._serialized_start=95
  _CREATEGAMERESPONSE._serialized_end=131
  _GETSHOTSREQUEST._serialized_start=133
  _GETSHOTSREQUEST._serialized_end=166
  _GETSHOTSRESPONSE._serialized_start=169
  _GETSHOTSRESPONSE._serialized_end=335
  _GETSHOTSRESPONSE_TEAMSHOTS._serialized_start=295
  _GETSHOTSRESPONSE_TEAMSHOTS._serialized_end=335
  _SHOTS._serialized_start=337
  _SHOTS._serialized_end=426
  _GETFOULSREQUEST._serialized_start=428
  _GETFOULSREQUEST._serialized_end=445
  _GETFOULSRESPONSE._serialized_start=447
  _GETFOULSRESPONSE._serialized_end=465
  _GETOFFSIDESREQUEST._serialized_start=467
  _GETOFFSIDESREQUEST._serialized_end=487
  _GETOFFSIDESRESPONSE._serialized_start=489
  _GETOFFSIDESRESPONSE._serialized_end=510
  _SETSHOTREQUEST._serialized_start=512
  _SETSHOTREQUEST._serialized_end=528
  _SETSHOTRESPONSE._serialized_start=530
  _SETSHOTRESPONSE._serialized_end=547
  _SETFOULREQUEST._serialized_start=549
  _SETFOULREQUEST._serialized_end=565
  _SETFOULRESPONSE._serialized_start=567
  _SETFOULRESPONSE._serialized_end=584
  _SETOFFSIDEREQUEST._serialized_start=586
  _SETOFFSIDEREQUEST._serialized_end=605
  _SETOFFSIDERESPONSE._serialized_start=607
  _SETOFFSIDERESPONSE._serialized_end=627
  _SETEVENTREQUEST._serialized_start=629
  _SETEVENTREQUEST._serialized_end=646
  _SETEVENTRESPONSE._serialized_start=648
  _SETEVENTRESPONSE._serialized_end=666
  _STATS._serialized_start=669
  _STATS._serialized_end=1179
# @@protoc_insertion_point(module_scope)
