install: 
	# try pip3 install -r requirements if the one below doesn't work
	pip install -r requirements.txt

gen-streamer: 
	cd streamer; \
	make gen;

make run-streamer: 
	cd streamer; \
	make run;
