-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE leagues (
    id uuid PRIMARY KEY,
    league_name character varying(255) NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX leagues_pkey ON leagues(id uuid_ops);
CREATE UNIQUE INDEX leagues_league_name_key ON leagues(league_name text_ops);
