install: 
	# try pip3 install -r requirements if the one below doesn't work
	pip install -r requirements.txt

gen-stats: 
	cd stats; \
	make gen;

run-stats: 
	cd stats; \
	make run;

gen-streamer: 
	cd streamer; \
	make gen;

run-streamer: 
	cd streamer; \
	make run;
